version: "3.9"
services:
  propositions:
    build: .
    image: edecision/propositions:latest
    ports:
      - "8084:8080"
    environment:
      - DB_URL=db_propositions:3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db_propositions
    networks:
      - edecision_network


  db_propositions:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SERVICE_AUTHENTIFICATION=${SERVICE_AUTHENTIFICATION}
      - SERVICE_EQUIPES=${SERVICE_EQUIPES}
      - SERVICE_PROJETS=${SERVICE_PROJETS}
      - SERVICE_VOTES=${SERVICE_VOTES}
    volumes:
      - db_propositions:/var/lib/mysql
    networks:
      - edecision_network
volumes:
  db_propositions:
    driver: local

networks:
  edecision_network:
    external: true
