version: "3.9"
services:
  equipes:
    build: .
    image: edecision/equipes:latest
    ports:
      - "8082:8080"
    environment:
      - DB_URL=db_equipes:3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db_equipes
    networks:
      - edecision_network


  db_equipes:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SERVICE_AUTHENTIFICATION=${SERVICE_AUTHENTIFICATION}
      - SERVICE_PROJETS=${SERVICE_PROJETS}
      - SERVICE_PROPOSITIONS=${SERVICE_PROPOSITIONS}
      - SERVICE_VOTES=${SERVICE_VOTES}
    volumes:
      - db_equipes:/var/lib/mysql
    networks:
      - edecision_network
volumes:
  db_equipes:
    driver: local

networks:
  edecision_network:
    external: true
